# config/services.yaml
services:
    App\Repository\UsersRepository:
        autowire: true
        # autres configurations éventuelles...
    App\Security\UsersAuthenticator:
        arguments:
            $userRepository: '@App\Repository\UsersRepository'
    # config/services.yaml
    Stripe\StripeClient:
        arguments:
            - '%env(STRIPE_SECRET_KEY)%'