controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

detail_livre:
    path: /livres/{id}
    controller: App\Controller\BookController::show
    methods: GET
    requirements:
        id: '\d+'



app_emprunts_index:
    path: '/emprunts'
    controller: 'App\Controller\EmpruntLivreController::index'
    methods: ['GET']
       

my_loans:
    path: /mes-emprunts
    controller: App\Controller\UsersController::myLoans
    methods: [GET]

extend_loan:
    path: /prolonger-emprunt/{id}
    controller: App\Controller\UsersController::extendLoan
    methods: [GET]       